//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMap
    {
        public int mapID { get; set; }
        public string MapofUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
